/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package KHATA;
//import KHATA.main;
public class App {
   

    public static void main(String[] args) {
        main m = new main();
        m.setVisible(true);
    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
}
