/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KHATA;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Suyash
 */
public class INTREST_WINDOW extends javax.swing.JFrame {
       static int dd,mm,yyyy;
       static item j;
       static float intrest;
            
    /**
     * Creates new form INTREST_WINDOW
     */
    public INTREST_WINDOW(item i,int d,int m,int y,float intr) {
        j=i;
        dd= d;
        mm=m;
        yyyy=y;
       intrest = intr;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("TOTAL INTREST :");

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText(String.valueOf(intrest)
        );

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText(String.valueOf(mm)
        );

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText(String.valueOf(yyyy)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("TILL DATE ");

        jLabel7.setBackground(new java.awt.Color(51, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText(String.valueOf(dd));

        jButton1.setText("PAID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabel6)
                    .addContainerGap(455, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
            j.out_dd = dd;
           j.out_mm = mm;
            j.out_yyyy = yyyy;
            j.intrest_paid = intrest;
            j.abhi_bhi_rakhi_h = false;
        
       File f_main  = new File("src\\main\\java\\CLOSED\\"+j.owner_name+"$paid"+j.intrest_paid+".txt");
          File F1,F2,F3,F4;
            String fname = j.owner_name +"$"+ j.item_id;
       F1 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\READABLE\\"+fname+".txt");
           try {
               f_main.createNewFile();
                
            FileWriter fw = new FileWriter(f_main);

            BufferedWriter bw = new BufferedWriter(fw);

            bw.write("ONWER NAME : "+j.owner_name);
            bw.newLine();
            bw.write("ITEM NAME : "+j.item_name);
            bw.newLine();
            bw.write("ITEM VALUE : "+j.value);
            bw.newLine();
            bw.write("RATE OF INTREST : "+j.rate);
            bw.newLine();
            bw.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
            bw.newLine();
            bw.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
            bw.newLine();
            bw.write("TOTAL INTREST : "+j.intrest_paid);
            bw.newLine();
            bw.write("REMARK : "+j.remark);
//                      String fname = j.owner_name +"$"+ j.item_id;
            File f_m  = new File("src\\main\\java\\DATABASE\\"+fname);
        File f_owner_name  = new File("src\\main\\java\\OWNER_N\\"+j.owner_name);
    File f_item_id  = new File("src\\main\\java\\ITEM_ID\\"+j.item_id);
   
//    f_m.renameTo("DELETED");
    
          File f1,f2,f3;
          f1 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\"+fname+".txt");
          f2= new File("src\\main\\java\\DELETED_OBJECTS\\BY_ITEM_ID\\"+j.item_id+".txt");
          f3 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_OWNER_NAME\\"+j.owner_name+".txt");
          
//      f1.createNewFile();
//      f2.createNewFile();
//      f3.createNewFile();
       
      
               System.err.println(f_m.renameTo(f1));
               System.err.println(f_owner_name.renameTo(f3));
               System.err.println(f_item_id.renameTo(f2));
//             System.err.println(   f1.createNewFile());
//              moveFile("D:/temp/test.txt", "D:/temp1/test.txt");
//               Files.move(Paths.get("src\\main\\java\\DATABASE\\"+fname), Paths.get("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\"+fname));
//    f_item_id.renameTo(f2);
//    f_owner_name.renameTo(f3);
                //-------------   FOR F1   ---------------------------------------------
//             F1 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\READABLE\\"+fname+".txt");
//               F1.createNewFile();
//                
//            FileWriter fw1 = new FileWriter(F1);
//
//            BufferedWriter bw1 = new BufferedWriter(fw1);
//
//            bw1.write("ONWER NAME : "+j.owner_name);
//            bw1.newLine();
//            bw1.write("ITEM NAME : "+j.item_name);
//            bw1.newLine();
//            bw1.write("ITEM VALUE : "+j.value);
//            bw1.newLine();
//            bw1.write("RATE OF INTREST : "+j.rate);
//            bw1.newLine();
//            bw1.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
//            bw1.newLine();
//            bw1.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
//            bw1.newLine();
//            bw1.write("TOTAL INTREST : "+j.intrest_paid);
//            bw1.newLine();
//            bw1.write("REMARK : "+j.remark);
//                   
//  //-------------   FOR F2   ---------------------------------------------
//             F2 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_ITEM_ID\\READABLE\\"+fname+".txt");
//               F2.createNewFile();
//                
//            FileWriter fw2 = new FileWriter(F2);
//
//            BufferedWriter bw2 = new BufferedWriter(fw2);
//
//            bw2.write("ONWER NAME : "+j.owner_name);
//           bw2.newLine();
//            bw2.write("ITEM NAME : "+j.item_name);
//            bw2.newLine();
//            bw2.write("ITEM VALUE : "+j.value);
//            bw2.newLine();
//            bw2.write("RATE OF INTREST : "+j.rate);
//            bw2.newLine();
//            bw2.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
//            bw2.newLine();
//            bw2.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
//            bw2.newLine();
//            bw2.write("TOTAL INTREST : "+j.intrest_paid);
//            bw2.newLine();
//            bw2.write("REMARK : "+j.remark);
//
////-------------   FOR F3   ---------------------------------------------
//             F3 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_OWNER_NAME\\READABLE\\"+fname+".txt");
//               F3.createNewFile();
//                
//            FileWriter fw3 = new FileWriter(F3);
//
//            BufferedWriter bw3 = new BufferedWriter(fw3);
//
//            bw3.write("ONWER NAME : "+j.owner_name);
//            bw3.newLine();
//            bw3.write("ITEM NAME : "+j.item_name);
//            bw3.newLine();
//            bw3.write("ITEM VALUE : "+j.value);
//            bw3.newLine();
//            bw3.write("RATE OF INTREST : "+j.rate);
//            bw3.newLine();
//            bw3.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
//            bw3.newLine();
//            bw3.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
//            bw3.newLine();
//            bw3.write("TOTAL INTREST : "+j.intrest_paid);
//            bw3.newLine();
//            bw3.write("REMARK : "+j.remark);
//
//            
//            
//            //-------------   FOR F4   ---------------------------------------------
//             F4 = new File("src\\main\\java\\READABLE DATABASE\\"+fname+".txt");
//               F4.createNewFile();
//                
//            FileWriter fw4 = new FileWriter(F2);
//
//            BufferedWriter bw4 = new BufferedWriter(fw4);
//
//            bw4.write("ONWER NAME : "+j.owner_name);
//            bw4.newLine();
//            bw4.write("ITEM NAME : "+j.item_name);
//            bw4.newLine();
//            bw4.write("ITEM VALUE : "+j.value);
//            bw4.newLine();
//            bw4.write("RATE OF INTREST : "+j.rate);
//            bw4.newLine();
//            bw4.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
//            bw4.newLine();
//            bw4.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
//            bw4.newLine();
//            bw4.write("TOTAL INTREST : "+j.intrest_paid);
//            bw4.newLine();
//            bw4.write("REMARK : "+j.remark);
//            
            bw.close();
            fw.close();
            
            new DONE().setVisible(true);
            this.dispose();
           } catch (IOException ex) {
               Logger.getLogger(INTREST_WINDOW.class.getName()).log(Level.SEVERE, null, ex);
           }
           
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTREST_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTREST_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTREST_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTREST_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTREST_WINDOW(j,dd, mm, yyyy,intrest).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
