/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KHATA;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.ObjectOutputStream;
import java.util.Date;

/**
 *
 * @author Suyash
 */
public class new_item extends javax.swing.JFrame {
static item j;

   /* void writef(String on ){   try{    
        
                       String fname = on;

//-------------   FOR F1   ---------------------------------------------
           File  F1 = new File("src\\main\\java\\READABLE DATABASE\\"+fname+".txt");
               F1.createNewFile();
                
            FileWriter fw1 = new FileWriter(F1);

            BufferedWriter bw1 = new BufferedWriter(fw1);
//            System.err.println("f1 created");

             bw1.write("ONWER NAME : "+j.owner_name);
            bw1.newLine();
            bw1.write("ITEM NAME : "+j.item_name);
            bw1.newLine();
            bw1.write("ITEM VALUE : "+j.value);
            bw1.newLine();
            bw1.write("RATE OF INTREST : "+j.rate);
            bw1.newLine();
            bw1.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
            bw1.newLine();
            bw1.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
            bw1.newLine();
            bw1.write("TOTAL INTREST : "+j.intrest_paid);
            bw1.newLine();
            bw1.write("REMARK : "+j.remark);
                   
  //-------------   FOR F2   ---------------------------------------------
         File    F2 = new File("src\\main\\java\\ITEM_ID\\READABLE\\"+j.item_id+".txt");
               F2.createNewFile();
                
            FileWriter fw2 = new FileWriter(F2);

            BufferedWriter bw2 = new BufferedWriter(fw2);

             bw2.write("ONWER NAME : "+j.owner_name);
           bw2.newLine();
            bw2.write("ITEM NAME : "+j.item_name);
            bw2.newLine();
            bw2.write("ITEM VALUE : "+j.value);
            bw2.newLine();
            bw2.write("RATE OF INTREST : "+j.rate);
            bw2.newLine();
            bw2.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
            bw2.newLine();
            bw2.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
            bw2.newLine();
            bw2.write("TOTAL INTREST : "+j.intrest_paid);
            bw2.newLine();
            bw2.write("REMARK : "+j.remark);

//-------------   FOR F3   ---------------------------------------------
         File    F3 = new File("src\\main\\java\\OWNER_N\\READABLE\\"+j.owner_name+".txt");
               F3.createNewFile();
                
            FileWriter fw3 = new FileWriter(F3);
BufferedWriter bw3 = new BufferedWriter(fw3);
               bw3.write("ONWER NAME : "+j.owner_name);
            bw3.newLine();
            bw3.write("ITEM NAME : "+j.item_name);
            bw3.newLine();
            bw3.write("ITEM VALUE : "+j.value);
            bw3.newLine();
            bw3.write("RATE OF INTREST : "+j.rate);
            bw3.newLine();
            bw3.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
            bw3.newLine();
            bw3.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
            bw3.newLine();
            bw3.write("TOTAL INTREST : "+j.intrest_paid);
            bw3.newLine();
            bw3.write("REMARK : "+j.remark);
    
    }catch(Exception e){e.printStackTrace();}}
    */
    /**
     * Creates new form new_item
     */
    public new_item() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        placed_by = new javax.swing.JTextField();
        owner = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        MM = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        item_name = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        remark = new javax.swing.JTextField();
        YYYY = new javax.swing.JTextField();
        DD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("NEW ITEM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ITEM NUMBER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("OWNER NAME");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("VALUE");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ITEM NAME");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("RATE OF INTREST");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("WHO PLACED*");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DATE OF IN");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("REMARK (IF ANY)");

        placed_by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placed_byActionPerformed(evt);
            }
        });

        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });

        MM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMActionPerformed(evt);
            }
        });

        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });

        item_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_nameActionPerformed(evt);
            }
        });

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });

        remark.setText("NO");
        remark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remarkActionPerformed(evt);
            }
        });

        YYYY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YYYYActionPerformed(evt);
            }
        });

        DD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDActionPerformed(evt);
            }
        });

        jLabel10.setText("DD");

        jLabel11.setText("MM");

        jLabel12.setText("YYYY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remark)
                            .addComponent(owner)
                            .addComponent(number)
                            .addComponent(item_name)
                            .addComponent(value)
                            .addComponent(placed_by)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 61, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placed_by, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(602, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(516, 516, 516)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void placed_byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placed_byActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placed_byActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void MMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMActionPerformed

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateActionPerformed

    private void item_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_nameActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void remarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remarkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     try{
         String owner_name = owner.getText();
    String item_id  = number.getText();
      String item_name0 = item_name.getText();  
    int value0 = Integer.parseInt(value.getText());
    int dd ,yyyy,mm,d = 0,m = 0,y = 0;
    dd = Integer.parseInt(DD.getText());
    mm = Integer.parseInt(MM.getText());
    yyyy= Integer.parseInt(YYYY.getText());
    Date d_in = new Date(yyyy,mm,dd);
//= Date.parse(date_of_in.getText());
       Float rate0= Float.valueOf(rate.getText());
     String placed_by0 = placed_by.getText();
    String remark0 = this.remark.getText();
   float Intrest_paid =0;
          item i = new item(owner_name, item_id, item_name0,  value0, dd, mm, yyyy,d,m,y,  rate0,  placed_by0, remark0,Intrest_paid);
           String fname = owner_name +"$"+ item_id;
//           System.err.println(i.getPath());
        j =i;
      
    File f_main  = new File("src\\main\\java\\DATABASE\\"+fname);
        File f_owner_name  = new File("src\\main\\java\\OWNER_N\\"+owner_name);
    File f_item_id  = new File("src\\main\\java\\ITEM_ID\\"+item_id);
   
            
    f_main.createNewFile();
   f_owner_name.createNewFile();
   f_item_id.createNewFile();
   
           ObjectOutputStream oos1 = new ObjectOutputStream(new FileOutputStream(f_main));
           ObjectOutputStream oos2 = new ObjectOutputStream(new FileOutputStream(f_owner_name));
           ObjectOutputStream oos3 = new ObjectOutputStream(new FileOutputStream(f_item_id));
          
           oos1.writeObject(i);
           oos2.writeObject(i);
           oos3.writeObject(i);
           
           
           
//           File f_main  = new File("src\\main\\java\\CLOSED\\"+j.owner_name+"$paid"+j.intrest_paid+".txt");
//          File F1,F2,F3;
////            String fname = j.owner_name +"$"+ j.item_id;
//       F1 = new File("src\\main\\java\\READABLE DATABASE\\"+fname+".txt");
//          
//               F1.createNewFile();
//                
//            FileWriter fw = new FileWriter(F1);
//
//            BufferedWriter bw = new BufferedWriter(fw);
//
//            bw.write("ONWER NAME : "+j.owner_name);
//            bw.newLine();
//            bw.write("ITEM NAME : "+j.item_name);
//            bw.newLine();
//            bw.write("ITEM VALUE : "+j.value);
//            bw.newLine();
//            bw.write("RATE OF INTREST : "+j.rate);
//            bw.newLine();
//            bw.write("DATE OF IN : "+j.in_dd+"/"+j.in_mm+"/"+j.in_yyyy);
//            bw.newLine();
//            bw.write("DATE OF OUT : "+j.out_dd+"/"+j.out_mm+"/"+j.out_yyyy);
//            bw.newLine();
//            bw.write("TOTAL INTREST : "+j.intrest_paid);
//            bw.newLine();
//            bw.write("REMARK : "+j.remark);
//                      String fname = j.owner_name +"$"+ j.item_id;
//            File f_m  = new File("src\\main\\java\\DATABASE\\"+fname);
//        File f_owner_name  = new File("src\\main\\java\\OWNER_N\\"+j.owner_name);
//    File f_item_id  = new File("src\\main\\java\\ITEM_ID\\"+j.item_id);
   
//    f_m.renameTo("DELETED");
    
//          File f1,f2,f3;
//          f1 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\"+fname+".txt");
//          f2= new File("src\\main\\java\\DELETED_OBJECTS\\BY_ITEM_ID\\"+j.item_id+".txt");
//          f3 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_OWNER_NAME\\"+j.owner_name+".txt");
          
//      f1.createNewFile();
//      f2.createNewFile();
//      f3.createNewFile();
       
      
              
//             System.err.println(   f1.createNewFile());
//              moveFile("D:/temp/test.txt", "D:/temp1/test.txt");
//               Files.move(Paths.get("src\\main\\java\\DATABASE\\"+fname), Paths.get("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\"+fname));
//    f_item_id.renameTo(f2);
//    f_owner_name.renameTo(f3);
      //   writef(fname);
       
//       File f_main  = new File("src\\main\\java\\CLOSED\\"+j.owner_name+"$paid"+j.intrest_paid+".txt");
        //  File F1,F2,F3,F4;
         //   String fname = j.owner_name +"$"+ j.item_id;
   //    F1 = new File("src\\main\\java\\DELETED_OBJECTS\\BY_HASHCODE\\READABLE\\"+fname+".txt");
           
            
      
      
         view_item t = new view_item(i);
//       new mywriter(i,fname);
           t.setVisible(true);
//           bw.close();
//       bw.flush();
           this.dispose();
       }catch(Exception e){
       e.printStackTrace();}
        
   
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void YYYYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YYYYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YYYYActionPerformed

    private void DDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DD;
    private javax.swing.JTextField MM;
    private javax.swing.JTextField YYYY;
    private javax.swing.JTextField item_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField number;
    private javax.swing.JTextField owner;
    private javax.swing.JTextField placed_by;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField remark;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
